### ISSUE TITLE
Module won't load on some system.

### ISSUE THREAD

**Issue by FredericHamel** [feeley/pyffi#1]
The command `python3-config` may not return the valid linker flags if it is a symbolic
link to the `python3.8-config`. In this case it requires the `--embed` option which
adds the link options to the python system library.

This is what `python3-config` output on my machine. The `-lpython3.8` is missing
causing a loading error in Gambit.
```
$ python3-config --ldflags
 -L/usr/lib  -lcrypt -lpthread -ldl  -lutil -lm -lm

$ python3-config --ldflags --embed
 -L/usr/lib -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm
```

The error is:
```
*** ERROR IN ##load-module-or-file -- /home/frederic/.gambit_userlib/github.com/feeley/pyffi/@/pyffi@gambit409003@C/pyffi.o1: undefined symbol: _PyUnicode_Ready
(##get-module 'github.com/feeley/pyffi)
```

The issue is that the `--embed` is considered an invalid argument by `python3-config` when it is a symbolic link to older version of python.

```
$ python3-config --ldflags
-L/usr/lib64 -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic

$ python3-config --ldflags --embed
Usage: /usr/bin/python3.6m-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir
```

**Comment by belmarca** [comment]
Note before fix: that is particular to Python 3.8: https://docs.python.org/3/whatsnew/3.8.html.

```
To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.
```

**Comment by belmarca** [comment]
I pushed a fix which should work. Can you try it?

**Comment by belmarca** [comment]
Works per @FredericHamel .
